### PR TITLE
fix: exclude *.ngfactory.ts and *.ngsummary.json

### PR DESCRIPTION
**Pull request by dherges**
- the distributable package of a library must contain the `*.metadata.json` files that are generated by `ngc`
- when `*.ngfactory.ts` and `*.ngsummary.json` are included (and published), consumers of the library may face compile errors

In my case, I started with the configuration from this starter. Both set of files where included in the dist folder and a consumer applicaiton encountered the following compile error:

```bash
ERROR in Error encountered resolving symbol values statically.
  Calling function 'OpaqueToken', function calls are not supported.
  Consider replacing the function or lambda with a reference to an exported function,
```

Excluding both `*.ngfactory.ts` and `*.ngsummary.json` solved the issue. I think it's safe to put the files in the `tmp` folder. If I am mistaken, please let me know.

### CODE REVIEW

**Comment by manekinekko** [comment]
What version of angular are you using in your host app?

**Comment by dherges** [comment]
@manekinekko 2.4.x with cli rc 2

@angular/cli: 1.0.0-rc.2
node: 6.9.5
os: darwin x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.2
@angular/compiler-cli: 2.4.9

**Comment by dherges** [comment]
This article suggests similar, see 4: Don’t include *.ngFactory.ts files in the npm package

https://medium.com/@isaacplmann/getting-your-angular-2-library-ready-for-aot-90d1347bcad#.1y5xu5605

**Comment by manekinekko** [comment]
It's more complicated than that. The correct way of distributing angular libraries is still being discussed internally. 
I'm gonna merge your code for now. But that's gonna change for the future.

thanks @dherges

**Comment by dherges** [comment]
Hi @manekinekko,

is there an issue in the official Angular repo tracking this?

At my employer, we're beginning to ship Angular libraries that need to be compiled for AoT users. If there is a discussion that we can contribute to or share our experiences, I'd like to!

**Pull request merged**
